### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by duegui** [easy-electrophysiology/load-heka-python#12]
Hello,

I am quite new into Python (just some basics of the language). 

I am working with HEKA files obtained using Patchmaster. I would need to extract the data from different sweeps and series into Python. 

I am trying to iuse your package, but I have know idea on how to get started. I am using PyCharm Community. I downloaded all contents (as a ZIP) and extracted them into a folder within the project. I marked this folder as Source folder, however, when I run the main file (load_heka.py), I get an error:

`Traceback (most recent call last):
  File "C:\Users\fernadi1\PycharmProjects\pythonProject\HEKA Loader\load_heka.py", line 4, in <module>
    from .trees.SharedTrees import BundleHeader, BundleItems, UserParamDescrType, LockInParams_v9, AmplifierState_v9, UserParamDescrType, Description, \
ImportError: attempted relative import with no known parent package`

Is there any easier way to install and use the package?

Best,
Diego

**Comment by easy-electrophysiology** [comment]
Hi Diego,

Thanks for your question, you are correct this is not clear / optimal at all. An update has been made and merged into main branch. Now, if you re-clone the repo like you did previously, then:

1) In the PyCharm terminal (not the python console), change directory to the repo. This is the directory with the pyproject.toml file in it
2) type `pip install .`
3) confirm installation with `pip show load_heka_python`

Now if you re-start a new python console, and type
`from load_heka_python.load_heka import LoadHeka`

This should work, these instructions are now also on the front page. Thanks for your question, please let me know if anything is not working or is not clear.

Cheers,
Joe
