### ISSUE TITLE
Can I extract a table of stimulus parameter steps rather than analyzing the stimulus for changes in the 'voltage' command?

### ISSUE THREAD

**Issue by cudmore** [easy-electrophysiology/load-heka-python#14]
Is it possible to extract stimulus parameters from a dat file?

I would like to extract information about "epochs" within a given stimulus. Here, "epochs" would represent voltage-clamp steps. For example:
       -  start : start sample/time of an epoch
        - stop : stop sample/time of an epoch
        - amplitude : the amplitude of the step

```python

_record = 0  # the first group
_sweep = 2  # sweep 2 has 19 series

_stimIndex = 1  # The index into the stimulus (versus the recording which is 0)

path = 'path/to/my/local/heka/dat/file.dat'
with LoadHeka(path) as heka_file:
        numSeries = len(heka_file.pul["ch"][_record]["ch"][_sweep]["ch"])
        for _seriesIndex in range(numSeries):
                seriesHeader_stim = heka_file.pul["ch"][_record]["ch"][_sweep]["ch"][_seriesIndex]["ch"][_stimIndex]['hd']
                seriesData_stim = heka_file.pul["ch"][_record]["ch"][_sweep]["ch"][_seriesIndex]["ch"][_stimIndex]['data']
```

At this point I have a Heka header and the raw data.

My strategy right now is to analyze the data in `seriesData_stim` looking for transitions/steps. This seems overly complicated?

Is there any way to look in `seriesHeader_stim` to find where the steps occured and what the level of each step was?

Let me know if this is clear or confusing and I can provide more info...

Over and out, Robert

**Comment by easy-electrophysiology** [comment]
Hi @cudmore, thanks for raising this issue. It might be possible to find these parameters from the HEKA headers, but unfortunately this information is a little bit obscure. The best bet would be to parse the header information and grab the parameters of interest, but this might turn out to be more compelx than reading from the stimulus itself.

The code that generates the stimulus from the header information can be found [here](https://github.com/easy-electrophysiology/load-heka-python/blob/a6ff9579297d82836e71014db6d8f97659d677fb/load_heka_python/readers/stim_reader.py#L101).  In particular, the header information is extracted [here](https://github.com/easy-electrophysiology/load-heka-python/blob/a6ff9579297d82836e71014db6d8f97659d677fb/load_heka_python/readers/stim_reader.py#LL128C1-L128C1) and used to determine where the stimulus steps occur. For example, `seVoltageIncMode` holds the increment mode, if I remember correctly `seDeltaVIncrement` is the voltage increments and `seDeltaTIncrement` are the time increments.

I think the header for these stimulus parameters can be found at e.g.: ` stim_sweep["ch"][0]["ch"][0]['hd']`, but let me know if it is not there.
